x-envargs: &envargs
  environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_HOST=${POSTGRES_HOST}
    - POSTGRES_PORT=${POSTGRES_PORT}
  networks:
    - app-net

services:
  javaapp:
    <<: *envargs
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  database:
    build:
      dockerfile: db.Dockerfile
    ports:
      - 5432:5432
    <<: *envargs

networks:
  app-net:
    driver: bridge