name: Build CI

on: [push]
env:
  POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
  POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
  POSTGRES_DB: ${{ vars.POSTGRES_DB }}
  POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
  POSTGRES_USER: ${{ vars.POSTGRES_USER }}
jobs:
  build:
    runs-on: ubuntu-latest
    name: Teste de Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          cache: maven
          distribution: temurin
      - name: Validar variaveis de ambiente
        id: env_vars
        run: | 
            #!/bin/bash
            variables=( $POSTGRES_PASSWORD $POSTGRES_HOST $POSTGRES_DB $POSTGRES_PORT $POSTGRES_USER )
            ALL_NULL=false
            for item in "${variables[@]}"; do
              if [[ "$item" == "" ]]; then
                ALL_NULL=true
                break
              fi
              echo "::debug::$item"
            done
            echo "ALL_NULL=$$ALL_NULL" >> $GITHUB_OUTPUT
            if [[ "$ALL_NULL" = true ]]; then
                exit 1
            fi
            
      - name: Build Projeto java
        run: | 
            if [[ ${{ steps.env_vars.outputs.ALL_NULL }} == false ]]; then 
              mvn -B package --file pom.xml && exit 0;
            else exit 1; fi
      - name: Setup Docker Compose
        if: ${{ success() }}
        run: docker compose up
