name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      POSTGRES_USER: $ {{ vars.POSTGRES_USER }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v5.0.0
      with:
        java-version: '21'
        cache: maven
        distribution: temurin
    - name: Test Env variables
      run: | 
        variables=( $POSTGRES_PASSWORD $POSTGRES_HOST $POSTGRES_DB $POSTGRES_PORT $POSTGRES_USER )
        for item in "${variables[@]}"; do
          if [[ "$item" == "" ]]; then
            exit 1
          fi
        done;
    - name: Setup maven pkgs
      run: mvn -B package --file pom.xml
    - name: Setup Docker Compose
      run: docker compose up
