name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v5.0.0
      with:
        java-version: '21'
        cache: maven
        distribution: temurin
      env:
        POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
        POSTGRES_DB: ${{ env.POSTGRES_DB }}
        POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
        POSTGRES_USER: ${{ env.POSTGRES_USER }}

    - name: Setup maven pkgs
      run: mvn -B package --file pom.xml
    - name: Setup Docker Compose
      run: docker compose up
