name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v5.0.0
    - name: Setup maven pkgs
      run: mvn clean package
    - name: Setup Docker Compose
      run: docker compose up --force-recreate --no-deps --build 
